os: Visual Studio 2015

install:
    - git submodule update --init --recursive

    - cd build\buildtools-premake\bin
    - git clone --depth=1 --recursive -b release --single-branch https://github.com/premake/premake-core.git

    #- '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"'

    - cd premake-core
    - nmake -f Bootstrap.mak MSDEV=vs2015 windows
    - cd ..

    - premake.bat --version

build_script:
    - echo Building version:%appveyor_build_version%
    - echo %cd%
    - cmd: msbuild c:\projects\test-appveyor\build\vs2015\Playground.sln /t:build /p:Configuration=Release
