install:
    - git submodule update --init --recursive
    - cmd: c:\projects\test-appveyor\build\buildtools-premake\bin\build.bat
    - cmd: c:\projects\test-appveyor\build\buildtools-premake\bin\premake.bat --version

build_script:
    - echo Building version:%appveyor_build_version%
    - cmd: msbuild c:\projects\test-appveyor\build\vs2015\Playground.sln /t:build /p:Configuration=Release
