environment:
  matrix:
    - VS_VERSION: vs2012
    - VS_VERSION: vs2013
    - VS_VERSION: vs2015

configuration:
    - Debug

install:
    - git submodule update --init --recursive

    # test messages
    - appveyor AddMessage "this is a test message"

    # test chocolatey
    - choco install wget
    - choco list -localonly

    # test batch setup
    - build\setup-premake.bat
    - build\setup-sqlite.bat
    - build\setup-llvm.bat

    # test build system
    - cd build
    - dependencies\premake\premake5.exe %VS_VERSION%
    - cd ..

test_script:
    - output\bin\debug\TestCpp
    - output\bin\debug\TestCSharp
