environment:
  matrix:
    #- VS_VERSION: vs2012
    #- VS_VERSION: vs2013
    - VS_VERSION: vs2015

configuration:
    - Debug

install:
    - git submodule update --init --recursive

    # test messages
    - appveyor AddMessage "test message"
    - appveyor AddMessage "test warning" -Category Warning
    - appveyor AddMessage "test error"   -Category Error

    # test chocolatey
    - choco install wget
    - choco list -localonly

    # test batch setup
    - build\setup-premake.bat
        #- build\setup-sqlite.bat
        #- build\setup-llvm.bat

    # test build system
    - cd build
    - dependencies\premake\premake5.exe %VS_VERSION%
    - cd ..

test_script:
    - cd output\bin\$(configuration)
    - TestCpp.exe --r junit -o TestCpp.results.xml
    - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestCpp.results.xml))
    - TestCSharp.exe
    - cd ..

artifacts:
  # test artifacts
  - path: outout\bin\$(configuration)\TestCpp.exe
  - path: outout\bin\$(configuration)\TestCSharp.exe
