environment:
  matrix:
    - VS_VERSION: vs2012
    - VS_VERSION: vs2013
    - VS_VERSION: vs2015

configuration:
    - Debug

install:
    - git submodule update --init --recursive

    # test batch setup
    - setup-sqlite.bat

    # test powershell setup
    - ps: build/setup-dependencies.ps1

    # test build system
    - cd build
    - dependencies\premake\premake5.exe %VS_VERSION%
