environment:
  matrix:
    #- VS_VERSION: vs2012
    #- VS_VERSION: vs2013
    - VS_VERSION: vs2015

configuration:
    - Debug

install:
    - git submodule update --init --recursive

    # test messages
    - appveyor AddMessage "test message"
    - appveyor AddMessage "test warning" -Category Warning
    - appveyor AddMessage "test error"   -Category Error

    # test chocolatey
    - choco install wget
    - choco list -localonly

    # test batch setup
    - build\setup-premake.bat
        #- build\setup-sqlite.bat
        #- build\setup-llvm.bat

    # test build system
    - cd build
    - dependencies\premake\premake5.exe %VS_VERSION%
    - cd ..

test_script:
    - cd output\bin\debug
    - TestCpp.exe --r junit -o TestCpp.results.xml
    - TestCSharp.exe
    - cd ..\..\..

after_test:
    - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path output\bin\debug\TestCpp.results.xml))

artifacts:
  # test artifacts
  - path: outout\*.exe
