install:
    - git submodule update --init --recursive
    - echo %CD%
    - cd build\buildtools-premake\bin
    - ps: build.bat
    - ps: premake.bat --version

build_script:
    - echo Building version:%appveyor_build_version%
    - cmd: msbuild c:\projects\test-appveyor\build\vs2015\Playground.sln /t:build /p:Configuration=Release
