environment:
  matrix:
    - VS_VERSION: vs2012
    - VS_VERSION: vs2013
    - VS_VERSION: vs2015

configuration:
    - Debug

install:
    - git submodule update --init --recursive

    - mkdir test_sqlite
    - cd test_sqlite
    - appveyor DownloadFile https://www.sqlite.org/2016/sqlite-amalgamation-3110100.zip
    - appveyor DownloadFile https://www.sqlite.org/2016/sqlite-dll-win64-x64-3110100.zip
    - 7z x sqlite-amalgamation-3110100.zip
    - 7z x sqlite-dll-win64-x64-3110100.zip
    - dir
    - cd ..

    - cd build
    - appveyor DownloadFile https://github.com/premake/premake-core/releases/download/v5.0.0-alpha8/premake-5.0.0-alpha8-windows.zip
    - 7z x premake-5.0.0-alpha8-windows.zip
    - premake5.exe --version
    - premake5.exe %VS_VERSION%
    - cd ..
