environment:
  matrix:
    - VS_VERSION: vs2012
    - VS_VERSION: vs2013
    - VS_VERSION: vs2015

configuration:
    - Debug

install:
    - git submodule update --init --recursive

    - setup-premake.bat
    - setup-sqlite.bat

    - ps: build/setup-dependencies.ps1
